image: ubuntu:16.04

before_script:
- apt-get update
- apt-get install -y make g++ libboost-all-dev

stages:
- test
- build

test:
   stage: test

   script:
   - make test-service

   only:
   - master

   tags:
   - ubuntu
   - docker

build:
   stage: build

   script:
   - make build

   only:
   - master

   tags:
   - ubuntu
   - docker
