image: ubuntu:16.04

before_script:
- apt-get update
- apt-get install -y git
- git submodule update --init
- apt-get install -y make cmake g++ libboost-all-dev
- apt-get install -y doxygen graphviz
- apt-get install -y openjdk-9-jdk maven

stages:
- test
- build

test:
   stage: test

   script:
   - make test

   only:
   - master

   tags:
   - ubuntu
   - docker

build:
   stage: build

   script:
   - make build

   only:
   - master

   tags:
   - ubuntu
   - docker
