image: ubuntu:16.04

before_script:
- apt-get update
- apt-get install -y git
- git submodule update --init
- apt-get install -y make g++ libasio-dev
- apt-get install -y doxygen graphviz

stages:
- build
- test

build:
   stage: build

   script:
   - make build

   only:
   - master

   tags:
   - ubuntu
   - docker

test:
   stage: test

   script:
   - apt-get install -y openjdk-9-jdk maven
   - make test

   only:
   - master

   tags:
   - ubuntu
   - docker
